"""change uid nullable

Revision ID: b506192f7b3c
Revises: b7b1b307ee6d
Create Date: 2025-08-24 19:09:01.778117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b506192f7b3c'
down_revision: Union[str, Sequence[str], None] = 'b7b1b307ee6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'uid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_nullable=False
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'uid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_nullable=True
               )
    # ### end Alembic commands ###
